robot_hardware:
  plugin: "MockHardware"
joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster
diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  joints:
    - left_wheel_joint
    - right_wheel_joint
  parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
