controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      publish_rate: 50
      velocity_commands: true
      joints:
        - left_wheel_joint
        - right_wheel_joint
